version: "3"
services:
  mssql:
    container_name: eproject-mssql
    image: hiencoday363/eproject-mssql:latest
    ports:
      - "1433:1433"
    restart: on-failure
    volumes:
      - eproject:/mssql_data
    networks:
      local:

  backend:
    container_name: eproject-backend
    build:
      dockerfile: ./Dockerfile
      context: ./BaseProject
    image: eproject_backend:latest
    environment:
      DbServer: "mssql"
      DbPort: 1433
      DbUser: "SA"
      Password: "root@123456"
      Database: "api_dotnet"
    ports:
      - "8008:80"
    restart: on-failure
    volumes:
      - eproject:/source-code
    depends_on:
      - mssql
    networks:
      local:

  frontend:
    container_name: eproject-frontend
    build:
      dockerfile: ./Dockerfile.react
      context: ./React-FE
      args:
        - REACT_APP_API_BASE_URL=http://localhost:8008/
    image: eproject_frontend:latest
    ports:
      - "3003:3000"
    restart: on-failure
    volumes:
      - ./React-FE:/app-react
      - /app-react/node_modules
    depends_on:
      - mssql
      - backend
    networks:
      local:

volumes:
  eproject:

networks:
  local:
    driver: bridge
