FROM node:14-alpine

WORKDIR /app-react

COPY ./package*.json ./

RUN yarn install 

COPY . .

ARG REACT_APP_API_BASE_URL
ENV REACT_APP_API_BASE_URL=$REACT_APP_API_BASE_URL

ENV HOST 0.0.0.0

EXPOSE 3000

CMD [ "yarn", "start" ]
