version: "3"
services: 
  frontend:
    stdin_open: true
    tty: true
    container_name: frontend-react-app
    build:
      context: ./
      dockerfile: Dockerfile.fe
    image: eproject_frontend:latest
    ports:
      - "3001:3000"
    networks:
      - apinetproject3_local
    volumes:
      - ./:/app-react
      - /app-react/node_modules
networks:
  apinetproject3_local:
    external: true
    driver: bridge