// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace BaseProject.Models
{
    public partial class Bill
    {
        public decimal SupportCost { get; set; }
        public int? EmployeeId { get; set; }
        public int ClaimId { get; set; }
        public int? PolicyId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? IsDeleted { get; set; }
        [JsonIgnore]
        public virtual ClaimEmployee Claim { get; set; }
        [JsonIgnore]
        public virtual Employee Employee { get; set; }
        [JsonIgnore]
        public virtual Policy Policy { get; set; }
    }
}