// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Newtonsoft.Json;
using System;
using System.Collections.Generic;

namespace BaseProject.Models
{
    public partial class ClaimEmployee
    {
        public ClaimEmployee()
        {
            ClaimActions = new HashSet<ClaimAction>();
        }

        public int Id { get; set; }
        public int? Status { get; set; }
        public string Reason { get; set; }
        public decimal TotalCost { get; set; }
        public int? EmployeeId { get; set; }
        public int? PolicyId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? IsDeleted { get; set; }

        [JsonIgnore]
        public virtual Employee Employee { get; set; }
        [JsonIgnore]
        public virtual Policy Policy { get; set; }
        [JsonIgnore]
        public virtual Bill Bill { get; set; }
        [JsonIgnore]
        public virtual ICollection<ClaimAction> ClaimActions { get; set; }
    }
}