// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseProject.Models
{
    public partial class ClaimAction
    {
        public int Id { get; set; }
        public int ActionType { get; set; }
        public string Reason { get; set; }
        public int? CreatebyEmployeeId { get; set; }
        public int? CreatebyInsuranceAdminId { get; set; }
        public int? ClaimId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? IsDeleted { get; set; }

        public virtual ClaimEmployee Claim { get; set; }
    }
}