// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseProject.Models
{
    public partial class Contract
    {
        public Contract()
        {
            ContractPolicies = new HashSet<ContractPolicy>();
        }

        public int EmployeeId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public decimal? TotalAmount { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? IsDeleted { get; set; }

        public virtual Employee Employee { get; set; }
        public virtual ICollection<ContractPolicy> ContractPolicies { get; set; }
    }
}