// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseProject.Models
{
    public partial class Employee
    {
        public Employee()
        {
            Bills = new HashSet<Bill>();
            ClaimEmployees = new HashSet<ClaimEmployee>();
            PolicyOrders = new HashSet<PolicyOrder>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public decimal? Salary { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public DateTime? Joindate { get; set; }
        public string Designation { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? IsDeleted { get; set; }

        public virtual Contract Contract { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<ClaimEmployee> ClaimEmployees { get; set; }
        public virtual ICollection<PolicyOrder> PolicyOrders { get; set; }
    }
}