// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseProject.Models
{
    public partial class Employee
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public decimal? Salary { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public DateTime? Joindate { get; set; }
        public string Designation { get; set; }
        public string Address { get; set; }
        public string Contact { get; set; }
        public string State { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
    }
}