// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BaseProject.Models
{
    public partial class InsuranceCompany
    {
        public InsuranceCompany()
        {
            InsuranceAdmins = new HashSet<InsuranceAdmin>();
            Policies = new HashSet<Policy>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Url { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? IsDeleted { get; set; }

        public virtual ICollection<InsuranceAdmin> InsuranceAdmins { get; set; }
        public virtual ICollection<Policy> Policies { get; set; }
    }
}