// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace BaseProject.Models
{
    public partial class Policy
    {
        public Policy()
        {
            Bills = new HashSet<Bill>();
            ClaimEmployees = new HashSet<ClaimEmployee>();
            ContractPolicies = new HashSet<ContractPolicy>();
            PolicyOrders = new HashSet<PolicyOrder>();
        }

        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        public int SupportPercent { get; set; }
        [Required]
        public int DurationInDays { get; set; }
        [Required]
        public decimal Price { get; set; }
        [Required]
        public int? TypeId { get; set; }
        [Required]
        public int? CompanyId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? IsDeleted { get; set; }

        public virtual InsuranceCompany Company { get; set; }
        public virtual TypePolicy Type { get; set; }
        public virtual ICollection<Bill> Bills { get; set; }
        public virtual ICollection<ClaimEmployee> ClaimEmployees { get; set; }
        public virtual ICollection<ContractPolicy> ContractPolicies { get; set; }
        public virtual ICollection<PolicyOrder> PolicyOrders { get; set; }
    }
}